src/message/get-base-report/index.tsx, src/message/get-log/index.tsx, src/message/util.tsx
fix: OCPP dictates int to be 32 bit (31 bit resolution, 1 sign bit) original implementation was using 64 bit int causing too large numbers
=> fix: OCPP dictates int to be 32 bit

package-lock.json, src/components/data-model-table/association-selection.tsx, src/components/data-model-table/editable.tsx, src/components/form/array-field.tsx, src/components/form/index.tsx, src/components/form/nested-object-field.tsx, src/message/clear-cache/index.tsx, src/message/get-base-report/index.tsx, src/message/get-installed-certificate-ids/index.tsx, src/message/get-log/index.tsx, src/message/get-variables/index.tsx, src/message/index.tsx, src/message/remote-start/index.tsx, src/message/remote-start/model.ts, src/message/trigger-message/index.tsx, src/pages/charging-stations/index.tsx, src/pages/id-tokens/IdToken.tsx
- fix: get installed certificate ids and remote start missing necessary form props
- chore: fix build issues
- feat: adjusting remote start to use the AssociationSelection that is now supported via GenericForm instead of using `overrides`
- feat: changed sorting of message components in dropdown so that they appear alphabetically
- feat: enhancing Remote Start id token to also be an association selection
- feat: adding requestStartId to be randomly generated and provided as a pre-filled input field in Remote Start component
- refactor: breaking form into multiple components by creating array and nested object field components
- fix: fixing issue with association selection not working properly when being rendered via generic form within an array field as is the case with Get Variables …
=> fix: Issues & Enhancements

package-lock.json, src/components/data-model-table/association-selection.tsx, src/message/customer-information/index.tsx, src/message/index.tsx, src/message/trigger-message/index.tsx, src/model/CustomerInformation.ts, src/pages/additional-infos/create.tsx, src/pages/additional-infos/edit.tsx, src/pages/additional-infos/list.tsx, src/pages/additional-infos/show.tsx, src/queries/additionalInfo.ts, src/redux/selectionSlice.ts, src/redux/store.ts
This PR fixes two small bugs:
* If you don't include an EVSE in a TriggerMessage request, it will error
* If you successfully send a TriggerMessage request, it will error even though it succeeded
=> Bugfix: TriggerMessage action shouldn't require EVSE

src/components/form/index.tsx, src/message/queries.tsx, src/message/reset/index.tsx
Use the generic form instead of manually building it.
=> refactor: update reset to use generic form and correct EVSE selection.

package-lock.json, src/components/data-model-table/association-selection.tsx, src/components/data-model-table/editable.tsx, src/components/form/index.tsx, src/message/customer-information/index.tsx, src/model/CustomerInformation.ts, src/pages/evses/variable-attributes/components/Component.tsx, src/pages/evses/variable-attributes/components/queries.ts, src/redux/selectionSlice.ts, src/util/decorators/Hidden.tsx
OCTT - EVSEType representation alongside needed Redux Bug fixes. Fixed the issue where on opening the Set Variables action for a charging station and selecting a Component or Variable, 'EvseDatabaseId is shown when it should show EVSEID and ConnectorID
=> OCTT - EVSEType representation

package-lock.json, src/message/set-variables/index.tsx
- refactor: SetVariables request to use the new GenericForm implementation for supporting association selection for component and variable models
- feat: added missing AttributeType enum
=> Feature: SetVariables enhancements

package-lock.json, src/message/index.tsx, src/pages/charging-stations/index.tsx
The charging station page should have a sidebar with an admin actions dropdown admin actions:
Update Basic Auth Password
=> Charging station sidebar update

src/pages/id-tokens-infos/id-token-infos.tsx
Just Making the fields optional solved the problem when creating an Id Token Info without defining a Group Id Token Id and when editing removing the value from the field.
=> Fixing Optional Fields

src/components/truncate-display/index.tsx, src/message/update-firmware/index.tsx, src/model/CustomerInformation.ts, src/model/interfaces.ts
Made idToken optional in CustomerInformation request
=> CustomerInformation request requires idToken

.env, src/App.tsx
=> version added to UI

package.json, src/message/update-auth-password/index.tsx
- fix: unintentional issue where payload in request to update password was null if setOnCharger boolean was set to true
=> Fix - Update Password empty payload

package-lock.json, package.json, src/App.tsx, src/pages/charging-stations/queries.ts
Patch update:
- Fixing query typo preventing ChargingStations from being edits
- Fixing Hasura issue preventing live data for pk-based subscriptions
=> 0.3.0 > 0.3.1 fixing typo on station protocol in gql queries

src/dtos/charging.station.dto.tsx, src/dtos/start.transaction.dto.tsx, src/dtos/transaction.dto.tsx, src/dtos/transaction.event.dto.tsx, src/message/queries.tsx, src/pages/authorizations/detail/authorization.detail.tsx, src/pages/authorizations/queries.ts, src/pages/charging-stations/detail/charging.station.detail.tsx, src/pages/locations/list/locations.charging.stations.table.tsx, src/pages/transactions/columns.tsx, src/pages/transactions/detail/style.scss, src/pages/transactions/detail/transaction.detail.card.tsx, src/pages/transactions/detail/transaction.detail.tsx, src/pages/transactions/index.tsx, src/pages/transactions/list/transactions.list.tsx, src/pages/transactions/queries.ts, src/style.scss
=> Standardizing transaction list and details

src/pages/charging-stations/detail/charging.station.detail.card.content.tsx
=> Adjusting charging station details, location name

src/pages/overview/charger-activity/charger.activity.card.tsx, src/pages/overview/charger.row.tsx
=> Adjusting chargerActivityCard and chargerRow to show EVSE ID as requested.

src/pages/charging-stations/queries.ts, src/pages/charging-stations/upsert/charging.stations.upsert.tsx
=> Redirecting to the newly created charging station

src/pages/charging-stations/detail/charging.station.configuration.tsx
- Adding a Search field to Configuration tab, able to search through every column
=> Adding a Search field to Configuration tab, searching for every column.

src/pages/locations/upsert/locations.upsert.tsx
Removing Geocode feature from Location Upsert.
=> Removing Geocode from Location Create / Edit

src/message/queries.tsx, src/modals/remote-start/1.6/index.tsx, src/modals/remote-start/2.0.1/index.tsx, src/modals/remote-stop/1.6/index.tsx, src/modals/remote-stop/2.0.1/index.tsx, src/modals/reset/1.6/index.tsx, src/modals/reset/2.0.1/index.tsx, src/modals/shared/connector-selector/connector.selector.tsx, src/modals/shared/evse-selector/evse.selector.tsx
=> Fixing Evse & Connector id selector to allow manual entry w/ validation.

package.json, src/message/queries.tsx, src/pages/authorizations/upsert/authorization.upsert.tsx, src/pages/charging-stations/detail/charging.station.aggregated.data.tsx, src/pages/charging-stations/detail/charging.station.detail.tsx, src/pages/transaction-events/columns.tsx, src/pages/transaction-events/list/transaction.events.list.tsx, src/pages/transaction-events/queries.ts, src/pages/transactions/chart/index.ts, src/pages/transactions/detail/transaction.detail.tsx
patch release:
- Authorizations were being created with cacheExpiryDateTime being set to current time, that was fixed.
- Meter Value charts added to charging stations.
- Transaction events tab now includes 1.6 events, other messages related to transactions
=> 0.3.2 > 0.3.3, cacheExpiryDateTime set to undefined

index.html, src/App.tsx, src/components/map/map.location.picker.tsx, src/components/map/map.tsx, src/components/title/index.tsx, src/message/2.0.1/get-log/index.tsx, src/message/2.0.1/update-firmware/index.tsx, src/telemetry.ts, src/util/BaseRestClient.ts, src/util/auth/AuthProvider.ts, src/util/config.ts, src/util/geocoding.tsx, src/util/use-gql-custom.tsx
allows for env vars to be easily overridden.
=> replacing direct references to env vars with config object 
